### ISSUE TITLE
for multiple bam files

### ISSUE THREAD

**Issue by Ivymanman** [canzarlab/McSplicer#3]
Hi, it's my first time to  use mcsplicer for AS analysis. I found that it can only input one bam file and get one csv result for one sample,but it takes too much time  for analyzing more than 50 bam files, I'm confusing  how to fix this problem.Thanks

**Comment by israa-alqassem** [comment]
Hi, I'm sorry I didn't understand your question, could you clarify? 

McSplicer does not take BAM file as an input, but rather it takes signature counts, so you have to run SigCount first to generate signature counts. Please read the readme file carefully and try the example.

**Comment by Ivymanman** [comment]
I'm sorry for my unclear statement,this is my code for sample1 below, could you please tell me how to analysis more than one sample at the same time, I can just write a for loop to analyse other samples.

#step 1
./McSplicer/bin/exonRefine  /ref/gencode.v38.annotation.gtf  --prefix OUTPUT_PREFIX

#step2
./McSplicer/bin/sigcount ../1.mapping/sample1_Aligned.sortedByCoord.out.bam OUTPUT_PREFIX.gtf sample1.SigCount

#step3
python3 ./McSplicer/python_scripts/McSplicer.py \
		--gtf OUTPUT_PREFIX.gtf \
		--count_file sample1.SigCount.cnt" \
		--out_dir step3/sample1 \
		--read_len 76 \
		--prefix step3/sample1"_PREFIX"

**Comment by israa-alqassem** [comment]
Yes, McSplicer takes one count file at a time. I assume each of your samples contains genome-wide reads.

To analyze several samples run different processes of McSplicer, you can run them in parallel or sequentially like in a for-loop.

Hope this helps. Let me know if you have other questions.

**Comment by Ivymanman** [comment]
I got it! 
Thanks
